from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak
from reportlab.lib.units import inch
from datetime import datetime
import os
import hashlib
from typing import List, Dict, Any

def generate_evidence_pdf(target_data: Dict[str, Any], posts: List[Dict[str, Any]], leads: List[Dict[str, Any]], officer_name: str, case_number: str) -> str:
    """
    Generates a professional court-admissible PDF report using ReportLab.
    """
    file_name = f"NCB_Evidence_{case_number}.pdf"
    file_path = os.path.join("/tmp", file_name)
    
    doc = SimpleDocTemplate(file_path, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []
    
    # Custom styles
    header_style = ParagraphStyle('HeaderStyle', parent=styles['Heading1'], alignment=1, textColor=colors.navy)
    footer_style = ParagraphStyle('FooterStyle', parent=styles['Normal'], alignment=1, fontSize=8, textColor=colors.grey)
    confidential_style = ParagraphStyle('Confidential', parent=styles['Normal'], alignment=1, textColor=colors.red, fontSize=12, bold=True)
    
    # Cover Page
    elements.append(Paragraph("<b>NCB DrugNet Intelligence Platform</b>", header_style))
    elements.append(Spacer(1, 0.5 * inch))
    elements.append(Paragraph(f"<b>CONFIDENTIAL: LAW ENFORCEMENT USE ONLY</b>", confidential_style))
    elements.append(Spacer(1, 1 * inch))
    
    # Case Metadata
    metadata = [
        ["Report Generation Date:", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
        ["Case ID / Reference:", case_number],
        ["Reporting Officer:", officer_name],
        ["Status:", "OFFICIAL EVIDENCE BUNDLE"]
    ]
    t_meta = Table(metadata, colWidths=[2*inch, 3*inch])
    t_meta.setStyle(TableStyle([('ALIGN', (0,0), (-1,-1), 'LEFT'), ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold')]))
    elements.append(t_meta)
    elements.append(Spacer(1, 2 * inch))
    
    # Disclaimer
    disclaimer_text = "The information contained in this document is generated based on automated Open Source Intelligence (OSINT) techniques on public data. This report is intended for investigative leads only and should be corroborated with formal evidence collection procedures."
    elements.append(Paragraph(disclaimer_text, styles['Normal']))
    
    elements.append(PageBreak())
    
    # Section 1: Target Profile
    elements.append(Paragraph("<b>Section 1: Target Profile</b>", styles['Heading2']))
    t_profile_data = [
        ["Handle", target_data.get('handle', 'N/A')],
        ["Platform", target_data.get('platform', 'N/A')],
        ["Subscribers", str(target_data.get('subscriber_count', 0))],
        ["Risk Score", str(target_data.get('risk_score', 0))],
        ["First Seen", str(target_data.get('first_seen', 'N/A'))],
        ["Last Scanned", str(target_data.get('last_scanned', 'N/A'))]
    ]
    t_profile = Table(t_profile_data, colWidths=[2*inch, 3*inch])
    t_profile.setStyle(TableStyle([('BOX', (0,0), (-1,-1), 1, colors.black), ('GRID', (0,0), (-1,-1), 0.5, colors.grey)]))
    elements.append(t_profile)
    elements.append(Spacer(1, 0.5 * inch))
    
    # Section 2: OSINT Leads
    elements.append(Paragraph("<b>Section 2: Extracted Identity Leads</b>", styles['Heading2']))
    lead_rows = [["Type", "Value", "Confidence", "Geo/Source"]]
    for lead in leads:
        lead_rows.append([
            lead.get('lead_type', ''),
            lead.get('value', ''),
            lead.get('confidence', ''),
            lead.get('geo_country', lead.get('source', ''))
        ])
    t_leads = Table(lead_rows, colWidths=[1*inch, 2*inch, 1*inch, 1.5*inch])
    t_leads.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.navy),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey)
    ]))
    elements.append(t_leads)
    elements.append(Spacer(1, 0.5 * inch))
    
    # Section 3: Evidence Posts
    elements.append(Paragraph("<b>Section 3: Evidence Posts Table</b>", styles['Heading2']))
    post_rows = [["Timestamp", "Text Preview", "Hash", "Geo"]]
    for post in posts[:30]: # Limit posts for PDF readability
        post_rows.append([
            post.get('captured_at', '')[:10],
            post.get('raw_text', '')[:30] + "...",
            post.get('sha256_hash', '')[:10],
            "YES" if post.get('geo_lat') else "NO"
        ])
    t_posts = Table(post_rows, colWidths=[1*inch, 2.5*inch, 1.2*inch, 0.8*inch])
    t_posts.setStyle(TableStyle([('GRID', (0,0), (-1,-1), 0.5, colors.grey)]))
    elements.append(t_posts)
    
    # Footer on every page
    def add_footer(canvas, doc):
        canvas.saveState()
        p = Paragraph("Generated by NCB DrugNet Intelligence Platform — CONFIDENTIAL", footer_style)
        w, h = p.wrap(doc.width, doc.bottomMargin)
        p.drawOn(canvas, doc.leftMargin, h)
        canvas.restoreState()

    # Build PDF
    doc.build(elements, onFirstPage=add_footer, onLaterPages=add_footer)
    
    return file_path

def calculate_pdf_hash(file_path: str) -> str:
    """
    Calculates SHA-256 for the generated file for integrity verification.
    """
    sha = hashlib.sha256()
    with open(file_path, "rb") as f:
        while True:
            data = f.read(65536)
            if not data:
                break
            sha.update(data)
    return sha.hexdigest()
